# Generated by Django 4.2 on 2023-05-12 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='key',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photographer',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
